<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Destination_model');
        
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $data['destination'] = $this->Destination_model->get_all_destination();
        $this->load->view('layouts/homeMain',$data);
    }
}
