<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Destination extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Destination_model');
        $this->load->library('session');
    } 

    /*
     * Listing of destination
     */
    function index()
    {
        $data['destination'] = $this->Destination_model->get_all_destination();
        
        $data['_view'] = 'destination/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new destination
     */
    function add()
    {
        $rDate = date("Y-m-d");
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'DestinationTitle' => $this->input->post('DestinationTitle'),
				'CreatedBy' => $this->session->userdata('UserId'),
				'CreatedDate' => $rDate,
				'IsActive' => 1,
				'DestinationDetails' => $this->input->post('DestinationDetails'),
            );
            
            $destination_id = $this->Destination_model->add_destination($params);
            redirect('destination/index');
        }
        else
        {            
            $data['_view'] = 'destination/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a destination
     */
    function edit($DestinationId)
    {   
        // check if the destination exists before trying to edit it
        $data['destination'] = $this->Destination_model->get_destination($DestinationId);
        
        if(isset($data['destination']['DestinationId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'DestinationTitle' => $this->input->post('DestinationTitle'),
					'CreatedBy' => $this->input->post('CreatedBy'),
					'CreatedDate' => $this->input->post('CreatedDate'),
					'IsActive' => $this->input->post('IsActive'),
					'DestinationDetails' => $this->input->post('DestinationDetails'),
                );

                $this->Destination_model->update_destination($DestinationId,$params);            
                redirect('destination/index');
            }
            else
            {
                $data['_view'] = 'destination/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The destination you are trying to edit does not exist.');
    } 

    /*
     * Deleting destination
     */
    function remove($DestinationId)
    {
        $destination = $this->Destination_model->get_destination($DestinationId);

        // check if the destination exists before trying to delete it
        if(isset($destination['DestinationId']))
        {
            $this->Destination_model->delete_destination($DestinationId);
            redirect('destination/index');
        }
        else
            show_error('The destination you are trying to delete does not exist.');
    }
    
}
