<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itinerary extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Itinerary_model');
    } 

    /*
     * Listing of itinerary
     */
    function index()
    {
        $data['itinerary'] = $this->Itinerary_model->get_all_itinerary();
        
        $data['_view'] = 'itinerary/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new itinerary
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ToDate' => $this->input->post('ToDate'),
				'ActivitiesId' => $this->input->post('ActivitiesId'),
				'CreatedDate' => $this->input->post('CreatedDate'),
				'IsActive' => $this->input->post('IsActive'),
				'UserId' => $this->input->post('UserId'),
				'DestinationId' => $this->input->post('DestinationId'),
				'FromDate' => $this->input->post('FromDate'),
            );
            
            $itinerary_id = $this->Itinerary_model->add_itinerary($params);
            redirect('itinerary/index');
        }
        else
        {            
            $data['_view'] = 'itinerary/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a itinerary
     */
    function edit($ItineraryId)
    {   
        // check if the itinerary exists before trying to edit it
        $data['itinerary'] = $this->Itinerary_model->get_itinerary($ItineraryId);
        
        if(isset($data['itinerary']['ItineraryId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ToDate' => $this->input->post('ToDate'),
					'ActivitiesId' => $this->input->post('ActivitiesId'),
					'CreatedDate' => $this->input->post('CreatedDate'),
					'IsActive' => $this->input->post('IsActive'),
					'UserId' => $this->input->post('UserId'),
					'DestinationId' => $this->input->post('DestinationId'),
					'FromDate' => $this->input->post('FromDate'),
                );

                $this->Itinerary_model->update_itinerary($ItineraryId,$params);            
                redirect('itinerary/index');
            }
            else
            {
                $data['_view'] = 'itinerary/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The itinerary you are trying to edit does not exist.');
    } 

    /*
     * Deleting itinerary
     */
    function remove($ItineraryId)
    {
        $itinerary = $this->Itinerary_model->get_itinerary($ItineraryId);

        // check if the itinerary exists before trying to delete it
        if(isset($itinerary['ItineraryId']))
        {
            $this->Itinerary_model->delete_itinerary($ItineraryId);
            redirect('itinerary/index');
        }
        else
            show_error('The itinerary you are trying to delete does not exist.');
    }
    
}
