<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->helper('url');
        $this->load->library('session');
        $this->load->library('form_validation');

    }

    /*
     * Listing of users
     */
    function index()
    {
        $data['users'] = $this->User_model->get_all_users();

        $data['_view'] = 'user/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new user
     */
    function add()
    {
        $rDate = date("Y-m-d");
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'FirstName' => $this->input->post('FirstName'),
                'LastName' => $this->input->post('LastName'),
                'Address' => $this->input->post('Address'),
                'Email' => $this->input->post('Email'),
                'Password' => md5($this->input->post('Password')),
                'UserType' => $this->input->post('UserType'),
                'RegisterDate' => $rDate,
                'IsActive' => 1,
            );

            $email_check = $this->User_model->email_check($params['Email']);

            if ($email_check) {
                $user_id = $this->User_model->add_user($params);
                $this->session->set_flashdata('success_msg', 'Registered successfully.You may log in now.');
                redirect('user/login_view');

            } else {
                $this->session->set_flashdata('error_msg', 'User email already exists.Please try again.');
                redirect('user/add');


            }
        } else {
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main', $data);
        }
    }

    public function login_view()
    {
        if ($this->session->userdata("UserId") == '') {
            $this->load->view("user/login");
        } else {
            redirect('website/profile');
        }
    }

    function login_user()
    {
        $user_email = $this->input->post('Email');
        $user_password = md5($this->input->post('Password'));
        print_r($user_password);

        $this->form_validation->set_rules('Email', 'Email', 'trim|required|valid_email');
        $this->form_validation->set_rules('Password', 'Password', 'trim|required');

        if ($this->form_validation->run() == FALSE) {
            redirect('user/login_view');
        } else {
            $query = $this->db->query("SELECT * FROM users WHERE Email='$user_email' AND Password='$user_password'");
            if ($query->num_rows() == 1) {
                $row = $query->result_array();
                $this->session->set_userdata('UserId', $row[0]['UserId']);
                $this->session->set_userdata('FirstName', $row[0]['FirstName']);
                $this->session->set_userdata('LastName', $row[0]['LastName']);
                $this->session->set_userdata('Address', $row[0]['Address']);
                $this->session->set_userdata('Email', $row[0]['Email']);
                $this->session->set_userdata('UserType', $row[0]['UserType']);

                redirect('website/profile');
            } else {
                $this->session->set_flashdata('logerror_msg', 'These credentials do not match our records.');
                $this->load->view('user/login');
            }

        }
    }

    /*
     * Editing a user
     */
    function edit($UserId)
    {
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($UserId);

        if (isset($data['user']['UserId'])) {
            if (isset($_POST) && count($_POST) > 0) {
                if($this->input->post('Password')!='')
                {
                    $pass = md5($this->input->post('Password'));
                }
                else
                {
                    $pass = $this->input->post('oldPassword');
                }

                    $params = array(
                    'FirstName' => $this->input->post('FirstName'),
                    'LastName' => $this->input->post('LastName'),
                    'Address' => $this->input->post('Address'),
                    'Email' => $this->input->post('Email'),
                    'Password' => $pass,
                );

                $this->User_model->update_user($UserId, $params);
                redirect('user/index');
            } else {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The user you are trying to edit does not exist.');
    }

    /*
     * Deleting user
     */
    function remove($UserId)
    {
        $user = $this->User_model->get_user($UserId);

        // check if the user exists before trying to delete it
        if (isset($user['UserId'])) {
            $this->User_model->delete_user($UserId);
            redirect('user/index');
        } else
            show_error('The user you are trying to delete does not exist.');
    }

    function user_profile()
    {

        $this->load->view('user_profile.php');

    }

    public function user_logout()
    {

        $this->session->sess_destroy();
        redirect('/', 'refresh');
    }

}
