<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Activity_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get activity by AcitivityId
     */
    function get_activity($AcitivityId)
    {
        return $this->db->get_where('activities',array('AcitivityId'=>$AcitivityId))->row_array();
    }
        
    /*
     * Get all activities
     */
    function get_all_activities()
    {
        $this->db->order_by('ActivityId', 'desc');
        return $this->db->get('activities')->result_array();
    }
        
    /*
     * function to add new activity
     */
    function add_activity($params)
    {
        $this->db->insert('activities',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update activity
     */
    function update_activity($AcitivityId,$params)
    {
        $this->db->where('AcitivityId',$AcitivityId);
        return $this->db->update('activities',$params);
    }
    
    /*
     * function to delete activity
     */
    function delete_activity($AcitivityId)
    {
        return $this->db->delete('activities',array('AcitivityId'=>$AcitivityId));
    }
}
