<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itinerary_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get itinerary by ItineraryId
     */
    function get_itinerary($ItineraryId)
    {
        return $this->db->get_where('itinerary',array('ItineraryId'=>$ItineraryId))->row_array();
    }
        
    /*
     * Get all itinerary
     */
    function get_all_itinerary()
    {
        $this->db->order_by('ItineraryId', 'desc');
        return $this->db->get('itinerary')->result_array();
    }
        
    /*
     * function to add new itinerary
     */
    function add_itinerary($params)
    {
        $this->db->insert('itinerary',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update itinerary
     */
    function update_itinerary($ItineraryId,$params)
    {
        $this->db->where('ItineraryId',$ItineraryId);
        return $this->db->update('itinerary',$params);
    }
    
    /*
     * function to delete itinerary
     */
    function delete_itinerary($ItineraryId)
    {
        return $this->db->delete('itinerary',array('ItineraryId'=>$ItineraryId));
    }
}
