<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transportation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get transportation by TransportID
     */
    function get_transportation($TransportID)
    {
        return $this->db->get_where('transportation',array('TransportID'=>$TransportID))->row_array();
    }
        
    /*
     * Get all transportation
     */
    function get_all_transportation()
    {
        $this->db->order_by('TransportID', 'desc');
        return $this->db->get('transportation')->result_array();
    }
        
    /*
     * function to add new transportation
     */
    function add_transportation($params)
    {
        $this->db->insert('transportation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update transportation
     */
    function update_transportation($TransportID,$params)
    {
        $this->db->where('TransportID',$TransportID);
        return $this->db->update('transportation',$params);
    }
    
    /*
     * function to delete transportation
     */
    function delete_transportation($TransportID)
    {
        return $this->db->delete('transportation',array('TransportID'=>$TransportID));
    }
}
